# Generated by Django 5.1.1 on 2024-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='recipe_tip',
            new_name='recipe',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='tip',
            field=models.TextField(blank=True),
        ),
    ]
